{
 "title": "Chainlink",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "job", "label": "job", "query": "cl_ocr,  cl_ocr_link" },
   {
    "name": "job_name",
    "query": {
     "query": "label_values(pipeline_run_total_time_to_completion, job_name)"
    }
   },
   {
    "name": "task_type",
    "query": {
     "query": "label_values(pipeline_tasks_total_finished, task_type)"
    }
   },
   {
    "name": "job_spec_id",
    "label": "job_spec_id",
    "query": {
     "query": "label_values(flux_monitor_reported_value, job_spec_id)"
    }
   },
   {
    "name": "account",
    "label": "account",
    "query": {
     "query": "label_values(eth_balance, account)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Node status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active instances",
     "type": "stat",
     "gridPos": { "h": 6, "w": 2, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(up{job=~\"$job\"})"
      }
     ]
    },
    {
     "title": "Prometheus target status ",
     "type": "state-timeline",
     "gridPos": { "h": 6, "w": 12, "x": 2, "y": 1 },
     "targets": [
      {
       "expr": "up{job=~\"$job\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Node uptime",
     "type": "timeseries",
     "description": "now-process_start_time_seconds",
     "gridPos": { "h": 6, "w": 10, "x": 14, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "days" } },
     "targets": [
      {
       "expr": "(time() - process_start_time_seconds{job=~\"$job\"}) /86400",
       "legendFormat": "{{instance}} - {{job}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Balances and Profit ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "ETH Total",
     "type": "stat",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "eth_balance{job=~\"$job\", account=~\"$account\" }",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "ETH balance",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 20, "x": 4, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "eth_balance{job=~\"$job\"}",
       "legendFormat": "{{instance}} - {{job}}"
      }
     ]
    },
    {
     "title": "Current balance and predicting 10h further on 2h data",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "eth_balance{job=~\"$job\", account=~\"$account\" }",
       "legendFormat": "{{account}}_Balance"
      },
      {
       "expr": "predict_linear(eth_balance{job=~\"$job\", account=~\"$account\" }[120m], 10*3600)",
       "legendFormat": "{{account}}_Predict"
      }
     ]
    },
    {
     "title": "TX fee's",
     "type": "timeseries",
     "description": "Txn Fee is (Gas Price * Gas Used by Txn) in Ether",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "eth_balance{job=~\"$job\", account=~\"$account\" }-eth_balance{job=~\"$job\", account=~\"$account\"} offset $__interval <0",
       "legendFormat": "fee - {{account}}"
      }
     ]
    },
    {
     "title": "Changes the ETH balance (daily)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
     "targets": [
      {
       "expr": "increase(clamp_min( eth_balance{job=~\"$job\"}-eth_balance{job=~\"$job\"} offset 2m,0 )[1d:2m])",
       "legendFormat": "Refill {{instance}}"
      },
      {
       "expr": "delta(eth_balance{job=~\"$job\"}[1d]) - increase(clamp_min( eth_balance{job=~\"$job\"}-eth_balance{job=~\"$job\"} offset 2m,0 )[1d:2m])",
       "legendFormat": "Spent  {{instance}}"
      }
     ]
    },
    {
     "title": "Gas Price",
     "type": "timeseries",
     "description": "The current price per gas in wei\n\n1 WEI = 0.000000000000000001 ETHER\nShortened by Grafana to GWEI",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "gas_updater_set_gas_price{job=~\"$job\"}/10^9",
       "legendFormat": "gas_price - {{instance}}"
      }
     ]
    },
    {
     "title": "Gas Price Percentiles",
     "type": "timeseries",
     "description": "Gas price at given percentile",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 40 },
     "targets": [
      {
       "expr": "gas_updater_all_gas_percetiles{percentile!=\"100%\",job=~\"$job\"}/1000000000",
       "legendFormat": "{{percentile}} - {{instance}}"
      }
     ]
    },
    {
     "title": "Total LINK",
     "type": "stat",
     "gridPos": { "h": 9, "w": 2, "x": 0, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(link_balance{job=~\"$job\", method=~\"get_withdrawable|^0x.*\"})"
      }
     ]
    },
    {
     "title": "Link Balances",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 22, "x": 2, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "link_balance{job=~\"$job\", method=~\"get_withdrawable|^0x.*\"}",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "Changes the LINK balance ",
     "type": "timeseries",
     "description": "sum(delta(link_balance[1d]))<=0    \nsum(delta(link_balance[1d]))>0",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 59 },
     "targets": [
      {
       "expr": "sum(delta(link_balance{job=~\"$job\", method=~\"get_withdrawable|^0x.*\"}[1d]))<=0",
       "legendFormat": "Withdraw"
      },
      {
       "expr": "sum(delta(link_balance{job=~\"$job\", method=~\"get_withdrawable|^0x.*\"}[1d]))>0",
       "legendFormat": "Rewards"
      }
     ]
    },
    {
     "title": "Changes the LINK balance (daily) ",
     "type": "timeseries",
     "description": "sum(max_over_time(link_balance[1d]    \n-(min_over_time(link_balance[1d])>0))",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 67 },
     "targets": [
      {
       "expr": "sum(max_over_time(link_balance{job=~\"$job\",  method=~\"get_withdrawable|^0x.*\"}[1d]) - (min_over_time(link_balance{job=~\"$job\",  method=~\"get_withdrawable|^0x.*\"}[1d])>0))"
      }
     ]
    },
    {
     "title": "Changes the LINK balance (daily)",
     "type": "timeseries",
     "description": "sum(increase(link_balance[1d] offset 1d ))     \nсдвиг в один день",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 75 },
     "targets": [
      {
       "expr": "sum(increase(link_balance{job=~\"$job\", method=~\"get_withdrawable|^0x.*\"}[1d] offset 1d ))"
      }
     ]
    }
   ]
  },
  {
   "title": "Head info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Current Head",
     "type": "stat",
     "description": "The highest seen head number",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "head_tracker_current_head{job=~\"$job\"}"
      }
     ]
    },
    {
     "title": "The total number of heads seen per minute",
     "type": "timeseries",
     "description": "Bad if less than 1 block in a minute",
     "gridPos": { "h": 9, "w": 21, "x": 3, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "changes(head_tracker_heads_received{job=~\"$job\"}[1m])"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 8 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "head_tracker_current_head{job=~\"$job\"}",
       "legendFormat": "Last head seen"
      }
     ]
    },
    {
     "title": "Etherscan block number with error in last 30 tx",
     "type": "timeseries",
     "description": "Number of block with isError != 0 (with errors), doesn't count several errored tx in one block!",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "etherscan_tx_error_in_block{job=~\"$job\"}",
       "legendFormat": "Block_number"
      }
     ]
    },
    {
     "title": "Number of times a transaction reverted on-chain",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "tx_manager_num_tx_reverted{job=~\"$job\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Max number of currently unconfirmed blocks",
     "type": "timeseries",
     "description": "The max number of blocks any currently unconfirmed transaction has been unconfirmed for",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "max_unconfirmed_blocks{job=~\"$job\"}",
       "legendFormat": "Max unconfirmed block number"
      }
     ]
    },
    {
     "title": "The size of the run queue",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "run_queue_queue_size{job=~\"$job\"}",
       "legendFormat": "run_queue_queue_size"
      },
      {
       "expr": "increase(run_queue_runs_queued{job=~\"$job\"}[1m])",
       "legendFormat": "increase of run_queue_runs_queued"
      }
     ]
    },
    {
     "title": "Number of currently unconfirmed transactions",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "unconfirmed_transactions{job=~\"$job\"}",
       "legendFormat": "Unconfirmed tx number"
      }
     ]
    },
    {
     "title": "Number of gas bumps and exceeds_limit count",
     "type": "timeseries",
     "description": "change to 1m interval later",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "changes(tx_manager_num_gas_bumps{job=~\"$job\"}[3m])",
       "legendFormat": "gas_bumps-{{instance}}"
      },
      {
       "expr": "tx_manager_gas_bump_exceeds_limit{job=~\"$job\"}",
       "legendFormat": "exceeds_limit-{{instance}}"
      }
     ]
    },
    {
     "title": "Total connection errors to eth node ",
     "type": "timeseries",
     "description": "The total number of eth node connection errors",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 33 },
     "targets": [
      {
       "expr": "head_tracker_eth_connection_errors{job=~\"$job\"}",
       "legendFormat": "{{instance}} - {{job}}"
      }
     ]
    },
    {
     "title": "The length of time the oldest unconfirmed transaction has been in that state (in seconds). Will be 0 if there are no unconfirmed transactions.",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max_unconfirmed_tx_age{job=~\"$job\"}",
       "legendFormat": "{{instance}} - {{job}}"
      }
     ]
    },
    {
     "title": "Number of times gas bumping failed from exceeding the configured limit.",
     "type": "timeseries",
     "description": "Any counts of this type indicate a serious problem.",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 44 },
     "targets": [
      {
       "expr": "tx_manager_gas_bump_exceeds_limit{job=~\"$job\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Number of times a transaction reverted on-chain",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 49 },
     "targets": [
      {
       "expr": "tx_manager_num_tx_reverted{job=~\"$job\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Job data (aggregate)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Errored job runs",
     "type": "timeseries",
     "description": "must be no data, or plain line without increasing",
     "gridPos": { "h": 32, "w": 12, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "pipeline_tasks_total_finished{status=\"error\",task_type=~\"$task_type\",job=~\"$job\",job_name=~\"$job_name\"}",
       "legendFormat": " {{job_name}} - {{task_type}}"
      }
     ]
    },
    {
     "title": "OCR Job Runs",
     "type": "heatmap",
     "description": "Bucket means job number\nCount is number of runs per 1m\n",
     "gridPos": { "h": 32, "w": 12, "x": 12, "y": 4 },
     "targets": [
      {
       "expr": "changes(pipeline_tasks_total_finished{status=\"completed\",task_type=\"median\",job=~\"$job\"}[1m])",
       "legendFormat": "{{job_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Job data (details)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Status:completed",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(pipeline_tasks_total_finished{job=~\"$job\",task_type=~\"$task_type\",status=\"completed\",job_name=~\"$job_name\"})by(job_name)",
       "legendFormat": "{{job_name}}"
      }
     ]
    },
    {
     "title": "Status:error",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(pipeline_tasks_total_finished{job=~\"$job\",task_type=~\"$task_type\",status=\"error\",job_name=~\"$job_name\"})by(job_name)",
       "legendFormat": "{{job_name}}"
      }
     ]
    },
    {
     "title": "% part error tasks",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(sum(pipeline_tasks_total_finished{task_type=~\"$task_type\",status=\"error\",job_name=~\"$job_name\"})by(job_name))/(sum(pipeline_tasks_total_finished{task_type=~\"$task_type\",job_name=~\"$job_name\"})by(job_name))*100",
       "legendFormat": "{{job_name}} "
      }
     ]
    },
    {
     "title": "Time taken to fully execute the HTTP request",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "pipeline_task_http_fetch_time{job=~\"$job\"}",
       "legendFormat": "{{instance}}  -  {{pipeline_task_spec_id}}"
      }
     ]
    },
    {
     "title": "Size (in bytes) of the HTTP response body",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "pipeline_task_http_response_body_size{job=~\"$job\"}",
       "legendFormat": "{{instance}}  -  {{pipeline_task_spec_id}}"
      }
     ]
    },
    {
     "title": "How long each pipeline run took to finish (from the moment it was created)",
     "type": "timeseries",
     "description": "pipeline_run_total_time_to_completion",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "sum(pipeline_run_total_time_to_completion{job=~\"$job\",job_name=~\"$job_name\"})by(job_name)",
       "legendFormat": "{{job_name}}"
      }
     ]
    },
    {
     "title": "How long each pipeline task of type took to execute",
     "type": "timeseries",
     "description": "pipeline_task_execution_time",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "sum(pipeline_task_execution_time{job=~\"$job\",task_type=~\"$task_type\",job_name=~\"$job_name\"})by(job_name)",
       "legendFormat": "{{job_name}} "
      }
     ]
    },
    {
     "title": " Number of errors for each pipeline spec",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 60 },
     "targets": [
      {
       "expr": "pipeline_run_errors{job=~\"$job\"}",
       "legendFormat": "{{job_name}}"
      }
     ]
    },
    {
     "title": " The total number of pipeline runs that are awaiting execution",
     "type": "timeseries",
     "description": "pipeline_runs_queued",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "pipeline_runs_queued{job=~\"$job\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "The total number of pipeline task runs that are awaiting execution",
     "type": "timeseries",
     "description": "pipeline_task_runs_queued",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "pipeline_task_runs_queued{job=~\"$job\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "System stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of bytes allocated and still in use.",
     "type": "timeseries",
     "description": "go_memstats_alloc_bytes",
     "gridPos": { "h": 7, "w": 10, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "go_memstats_alloc_bytes{job=~\"$job\"}",
       "legendFormat": "{{instance}} - {{job}}"
      }
     ]
    },
    {
     "title": "Resident memory size in bytes.",
     "type": "timeseries",
     "description": "process_resident_memory_bytes",
     "gridPos": { "h": 7, "w": 9, "x": 10, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "process_resident_memory_bytes{job=~\"$job\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Information about the Go environment. ",
     "type": "stat",
     "gridPos": { "h": 7, "w": 5, "x": 19, "y": 6 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "go_info{job=~\"$job\"}",
       "legendFormat": "{{instance}}  |  {{version}}   |   {{job}}"
      }
     ]
    },
    {
     "title": "Explorer push events",
     "type": "timeseries",
     "description": "The number of events pushed up to explorer",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "stats_pusher_events_sent{job=~\"$job\"}",
       "legendFormat": "{{instance}} - {{job}}"
      }
     ]
    },
    {
     "title": "Health status by service",
     "type": "state-timeline",
     "gridPos": { "h": 16, "w": 24, "x": 0, "y": 19 },
     "targets": [
      {
       "expr": "health{job=~\"$job\"}",
       "legendFormat": "{{service_id}} - {{instance}}"
      }
     ]
    }
   ]
  },
  { "title": "FM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Job run per day",
   "type": "timeseries",
   "description": "This count can include failed and reverted txes\nhttps://etherscan.io/address/address_to_change#analytics",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(changes(adapter_perform_complete_total{status=\"completed\",task_type=\"ethtx\", job=~\"$job\"}[$__interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total job run count",
   "type": "timeseries",
   "description": "Must be bound to 0 with spikes when there are job runs",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "changes(run_queue_runs_queued{job=~\"$job\"}[100s])"
    }
   ]
  },
  {
   "title": "FM last reported price ( $job_spec_id )",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 17 },
   "repeat": "job_spec_id",
   "targets": [
    {
     "expr": "flux_monitor_reported_value{job=~\"$job\" ,job_spec_id=~\"$job_spec_id\"}",
     "legendFormat": "{{job_spec_id}}"
    }
   ]
  },
  {
   "title": "FM last reported round ",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "flux_monitor_reported_round{job=~\"$job\",job_spec_id=~\"$job_spec_id\"}",
     "legendFormat": "{{job_spec_id}}"
    }
   ]
  }
 ]
}